#created on: Aug 12, 2011
package com.jboss.examples.drools.cep.alerts

#list any import classes here.
import com.jboss.examples.drools.cep.alerts.model.Alert
import com.jboss.examples.drools.cep.alerts.model.AlertStatus
import com.jboss.examples.drools.cep.alerts.model.Attribute
import com.jboss.examples.drools.cep.alerts.model.DerivedAlert
import com.jboss.examples.drools.cep.alerts.model.Equipment
import com.jboss.examples.drools.cep.alerts.model.Link
import com.jboss.examples.drools.cep.alerts.model.SystemAlert
import com.jboss.examples.drools.cep.alerts.services.DataService


#declare any global variables here
global com.jboss.examples.drools.cep.alerts.services.CAPService capService;
global com.jboss.examples.drools.cep.alerts.services.DataService dataService;


rule "Your First Rule"
    ruleflow-group "Device2 Validation Rules"
    when
        $alert : Alert( )
    then
        System.out.println("Alert");
        Equipment $equipment = dataService.lookupEquipment( $alert.getDeviceName() );
        insert($equipment);
        System.out.println("Equipment inserted : " + $equipment.getDeviceName());
end

rule "Device Exists in Derived Alert"
    ruleflow-group "Verify Derived Alerts"
    when
        $derivedAlert : DerivedAlert(  )
        $alert : Alert( deviceName memberOf $derivedAlert.deviceNames )
    then
        $derivedAlert.addAlert( $alert );
        System.out.println("Alert contained in existing derived alert");
        System.out.println($derivedAlert);
end
