#created on: Aug 3, 2011
package com.jboss.examples.drools.cep.alerts.rules

#list any import classes here.
import com.jboss.examples.drools.cep.alerts.model.Alert;
import com.jboss.examples.drools.cep.alerts.model.Attribute;
import com.jboss.examples.drools.cep.alerts.model.DerivedAlert;
import com.jboss.examples.drools.cep.alerts.model.Equipment;
import com.jboss.examples.drools.cep.alerts.model.Link;
import com.jboss.examples.drools.cep.alerts.model.SystemAlert;
import com.jboss.examples.drools.cep.alerts.model.AlertStatus;

import com.jboss.examples.drools.cep.alerts.services.CAPService;
import com.jboss.examples.drools.cep.alerts.services.DataService;

#declare any global variables here
global com.jboss.examples.drools.cep.alerts.services.CAPService capService;
global com.jboss.examples.drools.cep.alerts.services.DataService dataService;

rule "Create New Alert When SystemAlert Arrives"
    ruleflow-group "Alert Flow Rules"
    when
        $s : SystemAlert( status == AlertStatus.ACTIVE )
    then
        Alert a = new Alert( $s );
        Link downStreamLink = dataService.lookupDownstreamLink( a.getDeviceName() );
        Link upStreamLink = dataService.lookupUpstreamLink( a.getDeviceName() );
        a.setUpstreamLink( upStreamLink );
        a.setDownstreamLink( downStreamLink );
        System.out.println("new SystemAlert received.  Creating Alert.");
        retract($s);
        insert(a);
end

